"""empty message

Revision ID: 581cd055f1d3
Revises: 51890c423a60
Create Date: 2018-03-28 09:52:18.155063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581cd055f1d3'
down_revision = '51890c423a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawler_topic', sa.String(), nullable=True),
    sa.Column('parser_topic', sa.String(), nullable=True),
    sa.Column('cache_key_base', sa.String(), nullable=True),
    sa.Column('status_key_base', sa.String(), nullable=True),
    sa.Column('record_key_base', sa.String(), nullable=True),
    sa.Column('max_queue_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_config')
    # ### end Alembic commands ###
