"""empty message

Revision ID: 593ae2c4b7ba
Revises: 
Create Date: 2018-03-22 14:08:34.906675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593ae2c4b7ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('feature', sa.String(length=32), nullable=True),
    sa.Column('space', sa.Integer(), nullable=True),
    sa.Column('headers', sa.String(length=1024), nullable=True),
    sa.Column('method', sa.String(length=8), nullable=True),
    sa.Column('proxy', sa.String(length=8), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature'),
    sa.UniqueConstraint('platform')
    )
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('feature', sa.String(length=32), nullable=True),
    sa.Column('package', sa.String(length=64), nullable=True),
    sa.Column('mould', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.Column('file_md5', sa.String(length=32), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'feature', name='_platform_feature_uc')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('modules')
    op.drop_table('main_task')
    # ### end Alembic commands ###
