"""empty message

Revision ID: 81a9c5d5621f
Revises: aeda0c53915f
Create Date: 2018-03-28 11:16:01.036791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a9c5d5621f'
down_revision = 'aeda0c53915f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_task', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_task', 'status')
    # ### end Alembic commands ###
