"""empty message

Revision ID: aeda0c53915f
Revises: 581cd055f1d3
Create Date: 2018-03-28 10:23:37.026212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeda0c53915f'
down_revision = '581cd055f1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redis_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('passwd', sa.String(), nullable=True),
    sa.Column('db', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('redis_config')
    # ### end Alembic commands ###
