"""empty message

Revision ID: bff17ff82ef3
Revises: 593ae2c4b7ba
Create Date: 2018-03-22 14:31:33.800129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff17ff82ef3'
down_revision = '593ae2c4b7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('modules', sa.Column('own', sa.String(length=16), nullable=True))
    # op.drop_constraint(u'_platform_feature_uc', 'modules', type_='unique')
    # op.create_unique_constraint('_own_platform_feature_uc', 'modules', ['own', 'platform', 'feature'])
    op.create_table('modules',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('own', sa.String(length=32), nullable=True),
                    sa.Column('platform', sa.String(length=32), nullable=True),
                    sa.Column('feature', sa.String(length=32), nullable=True),
                    sa.Column('package', sa.String(length=64), nullable=True),
                    sa.Column('mould', sa.String(length=32), nullable=True),
                    sa.Column('url', sa.String(length=1024), nullable=True),
                    sa.Column('version', sa.String(length=16), nullable=True),
                    sa.Column('file_md5', sa.String(length=32), nullable=True),
                    sa.Column('valid', sa.Boolean(), nullable=True),
                    sa.Column('timestamp', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('own', 'platform', 'feature', name='_own_platform_feature_uc')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'_platform_feature_uc', 'modules', ['platform', 'feature'])
    op.drop_constraint('_own_platform_feature_uc', 'modules', type_='unique')
    op.drop_column('modules', 'own')
    # ### end Alembic commands ###
